# Para usarlo, solamente reemplaze el número de token-userN, éste corresponde a la propiedad configurada en settings.json de .vscode. La variable user sólo cambia el número del usuaro que configura en name y email cuando se crea o se loguea el usuario.
@user = 2
@token = {{token-user2}}

### POST - USER CREATE NEW
POST {{url}}/api/auth/new
Content-Type: application/json
Connection: keep-alive

{
  "name": "user {{user}}",
  "email": "user{{user}}@mail.com",
  "password": "123456"
}

### POST - USER LOGIN
POST {{url}}/api/auth/
Content-Type: application/json
Connection: keep-alive

{
  "email": "user{{user}}@mail.com",
  "password": "123456"
}

### GET - USER RENEW TOKEN
GET {{url}}/api/auth/
Content-Type: application/json
Connection: keep-alive
x-token: {{token}}
